version: '3'
services:
  # api:
    # environment: # for a full list check the corresponding properties-builder file
    #   - DB_DATABASE: dashboarddb
    #   - DB_HOST: db
    #   - DB_PORT: 27017
    #   - DB_USERNAME: dashboarduser
    #   - DB_PASSWORD: dbpassword
    # volumes:
    #   - ./logs:/hygieia/logs

  # ui:
    # environment:

  github-collector:
    environment:
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboarddb
      - MONGO_HOST=db
      - MONGODB_HOST=db
      - MONGO_PORT=27017
      - MONGODB_PORT=27017
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=dashboarduser
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpassword
      - GITHUB_CRON=0 * * * * *
      - GITHUB_HOST=https://github.com/HansenWu123/
      - GITHUB_COMMIT_THRESHOLD_DAYS=15
      - GITHUB_ERROR_THRESHOLD=1
      # - GITHUB_KEY = 
      # - PERSONAL_ACCESS_TOKEN = 

  # jenkins-build-collector:
    # environment:

  # jenkins-cucumber-test-collector:
    # environment:

  # jira-collector:
    # environment:

  # sonar-codequality-collector:
    # environment:

  # subversion-collector:
    # environment:
